### ISSUE TITLE
Feature Request: Configurable Backup Behavior on Restore

### ISSUE THREAD

**Issue by 7eventy7** [Szum123321/textile_backup#164]
# Feature Request: Configurable Backup Behavior on Restore

## Current Behavior
When restoring a world from a backup, the mod:
1. Deletes the backup that is being restored from
2. Creates a new backup of the world state that is being replaced

## Proposed Change
Add configuration options to control the backup behavior during restore operations:

```yaml
# In config file
backup:
  createBackupOfOldWorld: true  # Whether to create a backup of the world being replaced during restore
  deleteBackupOnRestore: true   # Whether to delete the backup file after successful restore
```

## Rationale
- Some users may want to keep their backup history intact for safety or archival purposes
- Others may prefer the current behavior to avoid accumulating duplicate backups
- Having these as configurable options allows users to choose the backup strategy that best fits their needs

## Benefits
- Greater control over backup management
- Flexible backup retention strategies
- Prevents accidental loss of backup history for users who want to preserve it
- Still maintains the current behavior as the default for users who prefer it

## Implementation Notes
- Both options should default to `true` to maintain backward compatibility
- The backup creation/deletion steps should be handled after confirming the restore was successful
- Consider adding logging to clearly indicate when backups are created or deleted based on these settings

Would you find these configuration options useful? Please let me know if you have any questions or suggestions for improvement.
